"use client"

import { useEffect, useMemo, useState } from 'react'
import Link from 'next/link'
import { ArrowLeft, Heart, MessageCircle, Search, Sparkles, Users } from 'lucide-react'

type Member = { id:string; name:string; access:'academy'|'studio'; role:'student'|'teacher'|'admin'; bio:string; interests:string[]; conversationTopics:string[]; avatarColor:string; joinedAt:string }
type MyProfile = { interests:string[]; conversationTopics:string[] }
type Filter='all'|'academy'|'studio'|'my-tastes'
const colors:Record<string,string>={violet:'from-violet-500 to-fuchsia-500',blue:'from-blue-500 to-cyan-400',pink:'from-pink-500 to-rose-400',emerald:'from-emerald-500 to-teal-400',amber:'from-amber-400 to-orange-500',cyan:'from-cyan-400 to-blue-500'}

export default function CommunityPage(){
 const [members,setMembers]=useState<Member[]>([]);const [mine,setMine]=useState<MyProfile>({interests:[],conversationTopics:[]});const [search,setSearch]=useState('');const [filter,setFilter]=useState<Filter>('all');const [loading,setLoading]=useState(true);const [error,setError]=useState('')
 useEffect(()=>{Promise.all([fetch('/api/community/members',{cache:'no-store'}).then(r=>r.ok?r.json():Promise.reject()),fetch('/api/profile',{cache:'no-store'}).then(r=>r.ok?r.json():{profile:null})]).then(([community,profile])=>{setMembers(community.members||[]);if(profile.profile)setMine({interests:profile.profile.interests||[],conversationTopics:profile.profile.conversationTopics||[]})}).catch(()=>setError('No pudimos cargar la comunidad.')).finally(()=>setLoading(false))},[])
 const mineSet=useMemo(()=>new Set([...mine.interests,...mine.conversationTopics].map(v=>v.toLowerCase())),[mine])
 const visible=useMemo(()=>{const term=search.trim().toLowerCase();return members.filter(member=>{const hay=[member.name,member.bio,...member.interests,...member.conversationTopics].join(' ').toLowerCase();const matchesSearch=!term||hay.includes(term);const matchesFilter=filter==='all'||filter==='my-tastes'||member.access===filter;const shared=filter!=='my-tastes'||[...member.interests,...member.conversationTopics].some(v=>mineSet.has(v.toLowerCase()));return matchesSearch&&matchesFilter&&shared})},[members,search,filter,mineSet])
 return <main className="min-h-screen bg-[#0a0f1e] px-4 py-10 text-white sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><Link href="/dashboard" className="inline-flex items-center gap-2 text-sm font-semibold text-white/45 hover:text-white"><ArrowLeft className="h-4 w-4"/> Student area</Link><div className="mt-7 flex flex-col gap-6 border-b border-white/[0.07] pb-8 lg:flex-row lg:items-end lg:justify-between"><div className="max-w-3xl"><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-[.16em] text-purple-300"><Sparkles className="h-4 w-4"/> Koterie community</div><h1 className="mt-3 text-4xl font-bold tracking-tight sm:text-5xl">Find something in common.</h1><p className="mt-4 text-lg leading-8 text-white/48">Perfiles reales, intereses reales y ninguna información de contacto privada. La idea es facilitar conversaciones, no sumar ruido.</p></div><div className="grid w-full grid-cols-1 gap-2 sm:flex sm:w-auto sm:flex-wrap"><Link href="/profile" className="inline-flex items-center justify-center rounded-xl border border-white/10 bg-white/5 px-5 py-3 font-bold hover:bg-white/10">Editar mi perfil</Link><Link href="/academy-forum" className="inline-flex items-center justify-center gap-2 rounded-xl bg-purple-600 px-5 py-3 font-bold hover:bg-purple-500"><MessageCircle className="h-4 w-4"/> Join a conversation</Link></div></div>
 <div className="mt-7 flex flex-col gap-3 md:flex-row md:items-center"><div className="relative flex-1 md:max-w-md"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-white/30"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search name, interest or topic…" className="w-full rounded-xl border border-white/10 bg-white/[0.035] py-3 pl-10 pr-4 text-sm outline-none focus:border-purple-400/35"/></div><div className="grid grid-cols-2 gap-2 sm:flex sm:flex-wrap">{(['all','academy','studio','my-tastes'] as Filter[]).map(option=><button key={option} onClick={()=>setFilter(option)} className={`min-h-11 rounded-xl px-4 py-2.5 text-sm font-semibold transition ${filter===option?'bg-white text-slate-950':'border border-white/10 bg-white/5 text-white/55 hover:text-white'}`}>{option==='all'?'All':option==='academy'?'Academy':option==='studio'?'Studio':<span className="inline-flex items-center gap-1"><Heart className="h-3.5 w-3.5"/> Mis gustos</span>}</button>)}</div>{!loading&&!error&&<span className="text-xs text-white/25 md:ml-auto">{visible.length} member{visible.length===1?'':'s'}</span>}</div>
 <section className="mt-7">{loading&&<div className="rounded-3xl border border-white/[0.08] bg-white/[0.025] p-10 text-center text-sm text-white/35">Loading community…</div>}{error&&<div className="rounded-2xl border border-red-500/20 bg-red-500/10 p-5 text-sm text-red-200">{error}</div>}{!loading&&!error&&visible.length===0&&<div className="rounded-3xl border border-dashed border-white/10 p-8 text-center sm:p-12"><Users className="mx-auto h-10 w-10 text-white/20"/><h2 className="mt-4 text-xl font-bold">No matching members yet.</h2><p className="mt-2 text-sm text-white/35">Completá tus intereses o cambiá los filtros para encontrar más personas.</p></div>}{!loading&&!error&&visible.length>0&&<div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{visible.map(member=>{const shared=[...member.interests,...member.conversationTopics].filter(v=>mineSet.has(v.toLowerCase())).slice(0,2);const initials=member.name.split(/\s+/).map(p=>p[0]).join('').slice(0,2).toUpperCase();return <Link href={`/profile/${member.id}`} key={member.id} className="group rounded-2xl border border-white/[0.08] bg-white/[0.03] p-5 transition hover:-translate-y-1 hover:border-purple-400/25"><div className={`flex h-12 w-12 items-center justify-center rounded-2xl bg-gradient-to-br ${colors[member.avatarColor]||colors.violet} font-bold`}>{initials}</div><h2 className="mt-4 text-lg font-bold group-hover:text-purple-200">{member.name}</h2><div className="mt-2 flex flex-wrap items-center gap-2"><span className={`rounded-full px-2.5 py-1 text-[11px] font-bold uppercase tracking-[.1em] ${member.access==='studio'?'bg-pink-500/10 text-pink-300':'bg-blue-500/10 text-blue-300'}`}>{member.access}</span>{member.role!=='student'&&<span className="rounded-full bg-amber-500/10 px-2.5 py-1 text-[11px] font-bold uppercase tracking-[.1em] text-amber-300">{member.role}</span>}</div>{member.bio&&<p className="mt-3 line-clamp-2 text-sm leading-6 text-white/40">{member.bio}</p>}<div className="mt-4 flex flex-wrap gap-1.5">{(shared.length?shared:member.interests.slice(0,3)).map(item=><span key={item} className={`rounded-full px-2.5 py-1 text-[11px] ${shared.includes(item)?'bg-emerald-500/10 text-emerald-300':'bg-white/5 text-white/35'}`}>{shared.includes(item)?'✓ ':''}{item}</span>)}</div></Link>})}</div>}</section></div></main>
}
