"use client"

import Link from 'next/link'
import { HeroCards } from '@/components/dashboard/hero-cards'
import { PricingSection } from '@/components/dashboard/pricing-section'
import { ArrowRight, Bot, CalendarDays, Check, Film, MessageCircle, Mic2, Sparkles, Users, Video } from 'lucide-react'

const whatsapp = 'https://wa.me/5491162991211?text=Hola%20Ana%20Laura%2C%20vi%20Koterie%20y%20quiero%20consultar%20por%20las%20clases%20de%20ingl%C3%A9s.'

const features = [
  { icon: MessageCircle, title: 'Comunidad real', text: 'Foros para conversar, preguntar y compartir intereses. Sin perfiles ni conversaciones inventadas.' },
  { icon: Mic2, title: 'Práctica entre clases', text: 'Actividades semanales, speaking y herramientas digitales para mantener el idioma activo.' },
  { icon: Bot, title: 'Koterie Practice', text: 'Práctica guiada desde la plataforma. La capa de IA completa se activa solo cuando esté configurada y controlada.' },
  { icon: Film, title: 'Inglés fuera del aula', text: 'Películas, series, debates y propuestas para que el idioma se conecte con intereses reales.' },
]

export default function HomePage() {
  return (
    <div className="min-h-screen bg-[#0a0f1e] text-white">
      <main>
        <section className="relative overflow-hidden border-b border-white/[0.05]">
          <div className="absolute inset-0 bg-[radial-gradient(circle_at_18%_18%,rgba(124,58,237,0.18),transparent_34%),radial-gradient(circle_at_84%_2%,rgba(59,130,246,0.13),transparent_30%)]" />
          <div className="relative mx-auto grid max-w-7xl gap-10 px-4 py-12 sm:px-6 sm:py-16 md:py-20 lg:grid-cols-[1.05fr_.95fr] lg:gap-12 lg:px-8 lg:py-24">
            <div className="flex flex-col justify-center">
              <div className="mb-6 inline-flex w-fit items-center gap-2 rounded-full border border-purple-500/25 bg-purple-500/10 px-4 py-2 text-sm font-bold text-purple-300"><Sparkles className="h-4 w-4" /> Clases en vivo + práctica toda la semana</div>
              <h1 className="max-w-4xl text-[2.6rem] font-black leading-[1.03] tracking-tight sm:text-5xl md:text-6xl lg:text-7xl">Aprendé inglés y <span className="bg-gradient-to-r from-violet-400 via-fuchsia-400 to-pink-400 bg-clip-text text-transparent">seguí usándolo</span> cuando termina la clase.</h1>
              <p className="mt-6 max-w-2xl text-lg leading-8 text-white/55 sm:text-xl">Koterie combina clases con profesoras reales, comunidad y actividades para que el inglés forme parte de tu semana y no solamente de una videollamada.</p>
              <div className="mt-8 flex flex-col gap-3 sm:flex-row"><a href={whatsapp} target="_blank" rel="noreferrer" className="inline-flex w-full items-center justify-center gap-2 rounded-2xl bg-gradient-to-r from-violet-600 to-purple-600 px-7 py-4 font-black shadow-xl shadow-purple-500/20 transition hover:brightness-110 sm:w-auto">Quiero consultar <ArrowRight className="h-5 w-5" /></a><Link href="#pricing" className="inline-flex w-full items-center justify-center rounded-2xl border border-white/10 bg-white/5 px-7 py-4 font-bold text-white/85 transition hover:bg-white/10 sm:w-auto">Ver modalidades</Link></div>
              <div className="mt-8 flex flex-wrap gap-x-6 gap-y-3 text-sm font-semibold text-white/55"><span className="flex items-center gap-2"><Check className="h-4 w-4 text-emerald-300" /> 2 horas semanales</span><span className="flex items-center gap-2"><Check className="h-4 w-4 text-emerald-300" /> Online</span><span className="flex items-center gap-2"><Check className="h-4 w-4 text-emerald-300" /> Plataforma incluida</span></div>
            </div>

            <div className="relative flex items-center justify-center"><div className="absolute h-80 w-80 rounded-full bg-purple-600/15 blur-3xl" /><div className="relative w-full max-w-lg overflow-hidden rounded-[2rem] border border-white/[0.08] bg-white/[0.035] p-5 shadow-2xl shadow-black/30 backdrop-blur-xl sm:p-6"><img src="/isologo-premium.png" alt="Koterie Language Studio" className="mx-auto w-full max-w-[360px] rounded-3xl" /><div className="mt-5 grid gap-3 sm:grid-cols-2"><div className="rounded-2xl border border-blue-500/15 bg-blue-500/[0.06] p-4"><Video className="h-5 w-5 text-blue-300" /><p className="mt-3 font-black">Clases en vivo</p><p className="mt-1 text-sm leading-6 text-white/45">Grupales o individuales.</p></div><div className="rounded-2xl border border-fuchsia-500/15 bg-fuchsia-500/[0.06] p-4"><MessageCircle className="h-5 w-5 text-fuchsia-300" /><p className="mt-3 font-black">Koterie entre clases</p><p className="mt-1 text-sm leading-6 text-white/45">Comunidad, actividades y práctica.</p></div></div></div></div>
          </div>
        </section>

        <section id="spaces" className="mx-auto max-w-7xl px-4 py-14 sm:px-6 sm:py-18 lg:px-8 lg:py-20"><div className="mb-10 max-w-3xl"><p className="text-sm font-black uppercase tracking-[0.18em] text-blue-300">Dos espacios, una misma comunidad</p><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-4xl">Academy y Studio mantienen la identidad original de Koterie.</h2><p className="mt-4 text-lg leading-8 text-white/50">Academy acompaña a quienes todavía están consolidando su inglés. Studio propone conversaciones más exigentes para niveles avanzados. Los alumnos pueden crecer dentro de la misma comunidad.</p></div><HeroCards /></section>

        <section id="platform" className="border-y border-white/[0.05] bg-white/[0.018] py-16 sm:py-20 lg:py-24"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="grid gap-10 lg:grid-cols-[.85fr_1.15fr] lg:items-end"><div><p className="text-sm font-black uppercase tracking-[0.18em] text-purple-300">La diferencia de Koterie</p><h2 className="mt-3 text-4xl font-black tracking-tight sm:text-5xl">La clase es el comienzo, no el final.</h2><p className="mt-5 text-lg leading-8 text-white/50">La plataforma suma motivos reales para volver, hablar, escribir, escuchar y practicar durante toda la semana.</p></div><div className="grid gap-4 sm:grid-cols-2">{features.map(({icon:Icon,title,text})=><article key={title} className="rounded-3xl border border-white/[0.07] bg-white/[0.03] p-6 transition hover:border-purple-400/20 hover:bg-white/[0.045]"><div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-gradient-to-br from-violet-500/20 to-fuchsia-500/20 text-purple-200"><Icon className="h-5 w-5" /></div><h3 className="mt-5 text-xl font-black">{title}</h3><p className="mt-3 leading-7 text-white/48">{text}</p></article>)}</div></div></div></section>

        <section id="community" className="py-16 sm:py-20 lg:py-24"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="grid gap-8 lg:grid-cols-[1.05fr_.95fr]"><div className="rounded-[2rem] border border-white/[0.08] bg-gradient-to-br from-blue-950/70 to-slate-950 p-8 sm:p-10"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-blue-500/15 text-blue-300"><Users className="h-6 w-6" /></div><h2 className="mt-6 text-3xl font-black sm:text-4xl">Una comunidad para aprender con otros.</h2><p className="mt-4 max-w-2xl text-lg leading-8 text-white/50">Los miembros reales de Koterie pueden conversar por intereses, hacer preguntas y participar en Academy o Studio según su nivel de acceso.</p><div className="mt-7 flex flex-wrap gap-3"><Link href="/login" className="inline-flex items-center gap-2 rounded-xl bg-blue-500 px-5 py-3 font-black transition hover:bg-blue-400">Entrar al área de alumnos <ArrowRight className="h-4 w-4" /></Link><Link href="/community" className="inline-flex items-center gap-2 rounded-xl border border-white/10 bg-white/5 px-5 py-3 font-bold transition hover:bg-white/10">Ver comunidad</Link></div></div><div className="rounded-[2rem] border border-purple-500/20 bg-gradient-to-br from-purple-950/55 to-slate-950 p-8 sm:p-10"><MessageCircle className="h-8 w-8 text-purple-300" /><h3 className="mt-6 text-2xl font-black">Discord sigue siendo un complemento.</h3><p className="mt-4 leading-7 text-white/50">Puede servir para encuentros informales y actividades puntuales. La información académica y la comunidad principal quedan dentro de Koterie.</p><a href="https://discord.gg/5EaYtrz7R7" target="_blank" rel="noopener noreferrer" className="mt-7 inline-flex items-center gap-2 font-black text-purple-300 transition hover:text-white">Abrir Discord <ArrowRight className="h-4 w-4" /></a></div></div></div></section>

        <section id="pricing" className="border-y border-white/[0.05] bg-white/[0.018] py-16 sm:py-20 lg:py-24"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><PricingSection /></div></section>

        <section id="seminars" className="py-16 sm:py-20 lg:py-24"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="overflow-hidden rounded-[2rem] border border-amber-400/15 bg-gradient-to-br from-amber-500/[0.08] via-white/[0.025] to-purple-500/[0.06] p-8 sm:p-10 lg:p-12"><div className="grid gap-8 lg:grid-cols-[1fr_auto] lg:items-center"><div><div className="flex items-center gap-2 text-sm font-black uppercase tracking-[0.18em] text-amber-300"><CalendarDays className="h-4 w-4" /> Seminarios Koterie</div><h2 className="mt-4 max-w-4xl text-3xl font-black tracking-tight sm:text-4xl">Encuentros especiales, completamente en inglés.</h2><p className="mt-4 max-w-3xl text-lg leading-8 text-white/50">Son productos independientes para niveles avanzados y pueden estar abiertos a personas que no tomen clases regulares. La página muestra únicamente seminarios reales que hayan sido publicados.</p></div><Link href="/seminars" className="inline-flex items-center justify-center gap-2 rounded-2xl bg-amber-400 px-6 py-4 font-black text-slate-950 transition hover:bg-amber-300">Ver seminarios <ArrowRight className="h-4 w-4" /></Link></div></div></div></section>

        <section className="px-4 pb-24 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl overflow-hidden rounded-[2rem] border border-purple-400/20 bg-gradient-to-r from-violet-700 via-purple-700 to-fuchsia-700 px-6 py-12 text-center shadow-2xl shadow-purple-950/30 sm:px-12 sm:py-16"><h2 className="text-4xl font-black tracking-tight sm:text-5xl">¿Querés saber qué opción te conviene?</h2><p className="mx-auto mt-4 max-w-2xl text-lg leading-8 text-white/75">Escribile directamente a Ana Laura y contale tu nivel, tu objetivo y qué horarios tenés disponibles.</p><a href={whatsapp} target="_blank" rel="noreferrer" className="mt-8 inline-flex items-center gap-2 rounded-2xl bg-white px-7 py-4 font-black text-purple-700 transition hover:bg-purple-50">Hablar por WhatsApp <ArrowRight className="h-5 w-5" /></a></div></section>
      </main>

      <footer className="border-t border-white/[0.06] bg-[#070b16] py-12"><div className="mx-auto grid max-w-7xl gap-8 px-4 sm:px-6 md:grid-cols-[1fr_auto] md:items-end lg:px-8"><div><img src="/koterie-logo-transparent.png" alt="Koterie Language Studio" className="h-20 w-auto" /><p className="mt-2 max-w-xl text-sm leading-6 text-white/40">Clases reales, práctica continua y comunidad para usar inglés de verdad.</p></div><div className="flex flex-wrap gap-x-5 gap-y-2 text-sm text-white/40"><Link href="#pricing" className="hover:text-white">Clases</Link><Link href="#platform" className="hover:text-white">Plataforma</Link><Link href="#community" className="hover:text-white">Comunidad</Link><Link href="/seminars" className="hover:text-white">Seminarios</Link></div></div></footer>
    </div>
  )
}
